version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    env_file: ./Backend/.env
    networks:
      - react-express

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
    env_file: ./Frontend/.env
    networks:
      - react-express

networks:
  react-express:
    driver: bridge
